### ISSUE TITLE
Invalid handler specified

### ISSUE THREAD

**Issue by Kuchiru** [jasperslits/haithowifi#1]
Hey there,

Just wanted to try this out, can never have enough sensors in home assistant.
Unfortunately i'm getting an error when attempting to add the integration in home assistant.

`Config flow could not be loaded: {"message":"Invalid handler specified"}`

I've attempted to clear my browser cache, manually installing instead of via HACS but no dice.

I can install other custom components without issue from hacs.

**Comment by Kuchiru** [comment]
I am unable to add the integration, so no devices can be added yet.

To provide you with steps:
1) Add the repo in hacs
2) Install the custom integration & restart
3) Settings -> Devices & services -> add integration
4) Search for Itho addon and click it.
5) error is shown.

Doesn't appear that there are logs, however there are errors in the browser console.
I exported a HAR file for troubleshooting and attached it.

I tried clearing browser cache, incognito tab, removing the custom component and manually installing. rebooting many many times.

**Comment by jasperslits** [comment]
Thanks, will have a look later this evening.

**Comment by jasperslits** [comment]
Interesting. I am getting the same on a clean HA install. Unfortunately it's not something I've seen before and the error doesnt point to a specific line in the source code. Something, somewhere in HA has changed that caused this. But adding debug statements doesnt seem to help as there's nothing printed. Seems related to the MQTT message handling as it shows up every minute. To be continued

``2024-07-10 21:30:11.506 ERROR (Recorder) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/util/logging.py", line 105, in _async_wrapper
    await async_func(*args)
  File "/usr/src/homeassistant/homeassistant/components/mqtt/discovery.py", line 388, in async_integration_message_received
    result = await hass.config_entries.flow.async_init(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1267, in async_init
    flow, result = await self._async_init(flow_id, handler, context, data)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1287, in _async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1423, in async_create_flow
    handler = await _async_get_flow_handler(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2856, in _async_get_flow_handler
    raise data_entry_flow.UnknownHandler
homeassistant.data_entry_flow.UnknownHandler

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/util/logging.py", line 107, in _async_wrapper
    log_exception(format_err, *args)
  File "/usr/src/homeassistant/homeassistant/util/logging.py", line 94, in log_exception
    friendly_msg = format_err(*args)
                   ^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/mqtt/client.py", line 804, in _exception_message
    call_back_name = getattr(msg_callback.args[0], "__name__")
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute '__name__'. Did you mean: '__ne__'?
``

**Comment by jasperslits** [comment]
Fixed by alignment of domain name https://github.com/jasperslits/haithowifi/commit/4f3b8c276e0bf3795ce5a121ff50fd99453a094b

New release v1.1 created

**Comment by Kuchiru** [comment]
Awesome, will give it a try when i get home :)

**Comment by Kuchiru** [comment]
fixed!

Thank you for your hard work :+1:
