### ISSUE TITLE
HACS repeats v1.4

### ISSUE THREAD

**Issue by jasperslits** [jasperslits/haithowifi#24]
<img width="628" alt="image" src="https://github.com/user-attachments/assets/0f797cfc-5a37-4182-aeb7-7b1614a0d93a">

This shows up when trying to update via HACS / HA instead of using git pull / manual install.

**Comment by benjamin-dcs** [comment]
Looks like HACS already prefixes the title with the tag...?

**Comment by jasperslits** [comment]
I didnt see it for v1.3. I was working on the reconfigure for a bit and saw this. I accidentally assigned it to you.

**Comment by jasperslits** [comment]
I guess there is a check in HACS to avoid duplicate if tag == release, we can try that too

**Comment by jasperslits** [comment]
Also seen with releases of other integrations via HACS like Watchman: v0.6.5 - v0.6.5 2024-11-25
