### ISSUE TITLE
Current code not backwards compatible with 1.4

### ISSUE THREAD

**Issue by benjamin-dcs** [jasperslits/haithowifi#40]
Rather big version incoming. Might want to step up to `2.0`

**Comment by jasperslits** [comment]
I guess procedure should be: 
* Delete existing entries in config flow / Integration
* Upgrade to latest (e.g. 2.0)
* Redo configuration

**Comment by benjamin-dcs** [comment]
That's what I had in mind as well 👍

**Comment by jasperslits** [comment]
Updated instructions in release notes for upcoming v2.0.0 release
