### ISSUE TITLE
Include pir in remotes

### ISSUE THREAD

**Issue by benjamin-dcs** [jasperslits/haithowifi#41]
See title

**Comment by benjamin-dcs** [comment]
Assuming it's actually 0/1 for `presence`

**Comment by jasperslits** [comment]
I looked at it but found it questionable on what it actually represents and how useful it is. So what's a use-case for this sensor?

**Comment by benjamin-dcs** [comment]
It's just a 'free' presence sensor people can use for other automation so they don't need an extra pir. For example in the toilet, toggle a light.

**Comment by benjamin-dcs** [comment]
Of course, we should make sure it's an actual PIR. Looking at the device itself on the Itho website it indeed seems questionable

**Comment by benjamin-dcs** [comment]
Check
