### ISSUE TITLE
Add-on name change

### ISSUE THREAD

**Issue by jasperslits** [jasperslits/haithowifi#42]
Currently the integration shows up like this in HA:
<img width="406" alt="image" src="https://github.com/user-attachments/assets/a6424bb9-3c33-47fb-bc25-7909092a0ba7">

That's because of this entries in the manifest: 
https://github.com/jasperslits/haithowifi/blob/9c781e7042efa619b8fc6911fb29b7a23d54113c/custom_components/ithodaalderop/manifest.json#L3

Suggestion is to change the name from "Itho Add-on" to "Itho WiFi Add-on" for consistency.

**Comment by benjamin-dcs** [comment]
Agree

**Comment by jasperslits** [comment]
Pushed via https://github.com/jasperslits/haithowifi/commit/20a2b27b17b9ae0ffd80f112a7f6984426c35cf2
