### ISSUE TITLE
Explore simplifying message_received() methods

### ISSUE THREAD

**Issue by benjamin-dcs** [jasperslits/haithowifi#59]
Idea being that `message.payload` is never `""` and we never set `self.entity_description.state` in `definitions.py`, so it's never `not None`

```python
  if message.payload == "":
      value = None
  elif self.entity_description.state is not None:
      value = self.entity_description.state(message.payload)
  else:
```

**Comment by benjamin-dcs** [comment]
Also, can we share common code?

**Comment by jasperslits** [comment]
This seems to work without causing errors. 

```Python
            payload = json.loads(message.payload)
            json_field = self.entity_description.json_field
            value = payload.get(json_field, None)
```

Some other integrations use a lambda expression to set the value using the base entity but I don't think that adds value here: https://github.com/home-assistant/core/blob/445690588c855498b56561805ed652a12f36a21d/homeassistant/components/roomba/sensor.py#L43 as there are complex mappings so it's a mix of lambda and if statements . 

I doubt if more code sharing can be done if the message_received method is simplified.
