### ISSUE TITLE
Geen date zichtbaar in de HA Itho Add-on integration.

### ISSUE THREAD

**Issue by 01kjm01** [jasperslits/haithowifi#73]
Beste Jasper & @arjenhiemstra

Hebben jullie een idee hoe het komt dat de data vanuit MQTT niet in te lezen is in de home assistant sensor integratie.
Foto's bijgevoegd.
Ha draait naar volle tevredenheid in virtueel machine in truenas scale.
![Addon-arjan-1](https://github.com/user-attachments/assets/828cebff-87b2-4565-9218-0df00d88e33e)
![Addon-arjan-2](https://github.com/user-attachments/assets/877a9f08-487e-4a20-97a9-379cead893bf)
![Jasper slits haithowifi](https://github.com/user-attachments/assets/b139a63c-7c9e-4f8d-b19f-e4ad20f9b2fd)
![MQTT Explorer](https://github.com/user-attachments/assets/b3eb6605-c4bc-41d1-805b-640ac5764f4d)

**Comment by benjamin-dcs** [comment]
Voor een `CVE` moet je `MQTT Base Topics` vullen met `ithocve` (in de wifi addon dus)

**Comment by 01kjm01** [comment]
@benjamin-dcs Beja @arjenhiemstra

Benjamin thank you very much it works!
