### ISSUE TITLE
Translation typo: Requested Toom Temperature instead of Room

### ISSUE THREAD

**Issue by ovitters** [jasperslits/haithowifi#76]
There's a typo in the translation for requested_room_temp. It has it translated as _Requested **T**oom Temperature_ instead of _Requested **R**oom Temperature_. The T needs to be an R.

The error is in the following file:
https://github.com/jasperslits/haithowifi/blob/005a1d9242e705539604e6fa24e13ba2dde45bce/custom_components/ithodaalderop/translations/en.json#L105-L107

**Comment by benjamin-dcs** [comment]
Noticed as well. Fix is incorporated in https://github.com/jasperslits/haithowifi/pull/77
